### ISSUE TITLE
No login credentials for ubuntu image.

### ISSUE THREAD

**Issue by RaylynnKnight** [gl-inet/mv1000-ubuntu-image#1]
No login credentials are provided for the ubuntu image!   Can you please update the documentation to provide credentials for logging it to the ubuntu image?

**Comment by alzhao** [comment]
Just did it. The root password is goodlife and you need to change it. Do it as the first task after you install ubuntu.

**Comment by RaylynnKnight** [comment]
Thank you!  Just reviewed the updated document also!  Thanks for your quick response.
