### ISSUE TITLE
Enabling Cgroup Memory

### ISSUE THREAD

**Issue by savioruz** [gl-inet/mv1000-ubuntu-image#3]
How to enable cgroup memory on gl-inet mv1000 based on this ubuntu 18.04 ?

**Comment by handongming** [comment]
You can refer to:
https://github.com/gl-inet/mv1000-ubuntu-image#example-2-installing-a-cross-compiled-kernel-image-dtb-and-kernel-module
to pack a custom kernel with preconfigured rootfs.

To enable kernel config you can use refer
https://github.com/gl-inet/mv1000-ubuntu-kernel/blob/master/README.md
use "make menuconfig" after "make mvebu_v8_lsp_defconfig".
to choose cgroup related option I guess.
